name: TsunDocs
packages:
  Kanna:
    url: https://github.com/tid-kijyun/Kanna
    exactVersion: 5.2.7
  Smile:
    url: https://github.com/onmyway133/Smile
    exactVersion: 2.1.0
  TsunDocsKit:
    path: ./TsunDocsKit
options:
  defaultConfig: Release
  transitivelyLinkDependencies: false
  groupOrdering:
    - order:
      - Shared
      - iOS
      - macOS
      - MobileShareExtension
attributes:
  LastSwiftUpdateCheck: 1250
  LastUpgradeCheck: 1250
  ORGANIZATIONNAME: Tasuku Tozawa
configs:
  Debug: debug
  Release: release
schemes:
  TsunDocs (iOS):
    build:
      targets:
        TsunDocs (iOS):
          - analyzing
          - testing
          - running
          - profiling
          - archiving
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  TsunDocs (macOS):
    build:
      targets:
        TsunDocs (macOS):
          - analyzing
          - testing
          - running
          - profiling
          - archiving
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  MobileShareExtension:
    build:
      targets:
        MobileShareExtension:
          - running
          - testing
          - profiling
          - analyzing
          - archiving
    run:
      askForAppToLaunch: false
      config: Debug
      debugEnabled: false
      launchAutomaticallySubstyle: 2
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
settings:
  base:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
    MTL_FAST_MATH: YES
  configs:
    Debug:
      APP_GROUP: group.net.tasuwo.tsundocs
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      APP_GROUP: group.net.tasuwo.tsundocs
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  TsunDocs (iOS):
    type: application
    platform: iOS
    sources:
      - path: Shared
      - path: iOS
    dependencies:
      - target: MobileShareExtension
      - package: TsunDocsKit
        product: Domain
      - package: TsunDocsKit
        product: Persistence
      - package: TsunDocsKit
        product: CompositeKit
      - package: TsunDocsKit
        product: TsunDocsUIKit
      - package: TsunDocsKit
        product: PreviewContent
      - package: Smile
      - package: Kanna
    prebuildScripts:
      - name: SwiftLint
        runOnlyWhenInstalling: false
        path: scripts/run_swiftlint.sh
        shell: /bin/sh
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: iOS/iOS.entitlements
        DEVELOPMENT_TEAM: RY2377PP7S
        ENABLE_PREVIEWS: YES
        INFOPLIST_FILE: iOS/Info.plist
        IPHONEOS_DEPLOYMENT_TARGET: 15.0
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
        PRODUCT_BUNDLE_IDENTIFIER: net.tasuwo.tsundocs
        PRODUCT_NAME: TsunDocs
        SDKROOT: iphoneos
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1,2
      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Development
          PRODUCT_BUNDLE_IDENTIFIER: net.tasuwo.tsundocs
          PROVISIONING_PROFILE_SPECIFIER: match Development net.tasuwo.tsundocs
        Release:
          VALIDATE_PRODUCT: YES
          CODE_SIGN_IDENTITY: Apple Distribution
          PRODUCT_BUNDLE_IDENTIFIER: net.tasuwo.tsundocs
          PROVISIONING_PROFILE_SPECIFIER: match AppStore net.tasuwo.tsundocs
  TsunDocs (macOS):
    type: application
    platform: macOS
    sources:
      - path: Shared
      - path: macOS
    dependencies:
      - package: TsunDocsKit
        product: Domain
      - package: TsunDocsKit
        product: Persistence
      - package: TsunDocsKit
        product: CompositeKit
      - package: TsunDocsKit
        product: TsunDocsUIKit
      - package: TsunDocsKit
        product: PreviewContent
      - package: Smile
      - package: Kanna
    prebuildScripts:
      - name: SwiftLint
        runOnlyWhenInstalling: false
        path: scripts/run_swiftlint.sh
        shell: /bin/sh
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: macOS/macOS.entitlements
        COMBINE_HIDPI_IMAGES: YES
        DEVELOPMENT_TEAM: RY2377PP7S
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_PREVIEWS: YES
        INFOPLIST_FILE: macOS/Info.plist
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/../Frameworks'
        MACOSX_DEPLOYMENT_TARGET: 11.0
        PRODUCT_BUNDLE_IDENTIFIER: net.tasuwo.tsundocs
        PRODUCT_NAME: TsunDocs
        SDKROOT: macosx
        SWIFT_VERSION: 5.0
      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Development
          PRODUCT_BUNDLE_IDENTIFIER: net.tasuwo.tsundocs
          PROVISIONING_PROFILE_SPECIFIER: match Development net.tasuwo.tsundocs macos
        Release:
          CODE_SIGN_IDENTITY: Apple Distribution
          PRODUCT_BUNDLE_IDENTIFIER: net.tasuwo.tsundocs
          PROVISIONING_PROFILE_SPECIFIER: match AppStore net.tasuwo.tsundocs macos
  MobileShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: MobileShareExtension
    dependencies:
      - package: TsunDocsKit
        product: Domain
      - package: TsunDocsKit
        product: Persistence
      - package: TsunDocsKit
        product: CompositeKit
      - package: TsunDocsKit
        product: MobileShareExtensionUIKit
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: MobileShareExtension/MobileShareExtension.entitlements
        DEVELOPMENT_TEAM: RY2377PP7S
        INFOPLIST_FILE: MobileShareExtension/Info.plist
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
          - "@executable_path/../../Frameworks"
        SKIP_INSTALL: YES
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: net.tasuwo.tsundocs.ext-mobile-share
          PROVISIONING_PROFILE_SPECIFIER: match Development net.tasuwo.tsundocs.ext-mobile-share
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PRODUCT_BUNDLE_IDENTIFIER: net.tasuwo.tsundocs.ext-mobile-share
          PROVISIONING_PROFILE_SPECIFIER: match AppStore net.tasuwo.tsundocs.ext-mobile-share
