name: TsunDocs
options:
  defaultConfig: Release
  transitivelyLinkDependencies: false
  groupOrdering:
    - order:
      - Shared
      - Preview Content
      - iOS
      - macOS
      - CompositKit
attributes:
  LastSwiftUpdateCheck: 1250
  LastUpgradeCheck: 1250
  ORGANIZATIONNAME: Tasuku Tozawa
configs:
  Debug: debug
  Release: release
packages:
  Smile:
    url: https://github.com/onmyway133/Smile
    from: 2.1.0
schemes:
  TsunDocs (iOS):
    build:
      targets:
        TsunDocs (iOS):
          - analyzing
          - testing
          - running
          - profiling
          - archiving
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  TsunDocs (macOS):
    build:
      targets:
        TsunDocs (macOS):
          - analyzing
          - testing
          - running
          - profiling
          - archiving
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
settings:
  base:
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
    MTL_FAST_MATH: YES
    PRODUCT_NAME: TsunDocs
  configs:
    Debug:
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  TsunDocs (iOS):
    type: application
    platform: iOS
    sources:
      - path: Shared
      - path: Preview Content
      - Preview Content/Preview Assets.xcassets
      - path: iOS
    dependencies:
      - target: CompositKit_iOS
      - package: Smile
    prebuildScripts:
      - name: SwiftLint
        runOnlyWhenInstalling: false
        path: scripts/run_swiftlint.sh
        shell: /bin/sh
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: RY2377PP7S
        ENABLE_PREVIEWS: YES
        INFOPLIST_FILE: iOS/Info.plist
        IPHONEOS_DEPLOYMENT_TARGET: 14.0
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
        PRODUCT_BUNDLE_IDENTIFIER: net.tasuwo.tsundocs
        PRODUCT_NAME: TsunDocs
        SDKROOT: iphoneos
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1,2
        DEVELOPMENT_ASSET_PATHS: 'Preview\ Content'
      configs:
        Debug:
        Release:
          VALIDATE_PRODUCT: YES
  TsunDocs (macOS):
    type: application
    platform: macOS
    sources:
      - path: Shared
      - path: Preview Content
      - Preview Content/Preview Assets.xcassets
      - path: macOS
    dependencies:
      - target: CompositKit_macOS
      - package: Smile
    prebuildScripts:
      - name: SwiftLint
        runOnlyWhenInstalling: false
        path: scripts/run_swiftlint.sh
        shell: /bin/sh
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: macOS/macOS.entitlements
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        DEVELOPMENT_TEAM: RY2377PP7S
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_PREVIEWS: YES
        INFOPLIST_FILE: macOS/Info.plist
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/../Frameworks'
        MACOSX_DEPLOYMENT_TARGET: 11.0
        PRODUCT_BUNDLE_IDENTIFIER: net.tasuwo.tsundocs
        PRODUCT_NAME: TsunDocs
        SDKROOT: macosx
        SWIFT_VERSION: 5.0
        DEVELOPMENT_ASSET_PATHS: 'Preview\ Content'
      configs:
        Debug:
        Release:
  CompositKit:
    type: framework
    platform: [iOS, macOS]
    sources:
      - path: CompositKit
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: YES
        DEVELOPMENT_TEAM: RY2377PP7S
        INFOPLIST_FILE: CompositKit/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: net.tasuwo.CompositKit
        PRODUCT_BUNDLE_IDENTIFIER[sdk=macosx*]: net.tasuwo.CompositKit
        PROVISIONING_PROFILE_SPECIFIER:
        PROVISIONING_PROFILE_SPECIFIER[sdk=macosx*]:
        SUPPORTS_MACCATALYST: NO
