///
/// @Generated by Mockolo
///

import CloudKit
import Combine
import CoreDataCloudKitHelper

public class CloudKitAvailabilityObservableMock: CloudKitAvailabilityObservable {
    public init() { }
    public init(availability: AnyPublisher<CloudKitAvailability?, Error>) {
        self._availability = availability
    }

    public private(set) var availabilitySetCallCount = 0
    private var _availability: AnyPublisher<CloudKitAvailability?, Error>! { didSet { availabilitySetCallCount += 1 } }
    public var availability: AnyPublisher<CloudKitAvailability?, Error> {
        get { return _availability }
        set { _availability = newValue }
    }

    public private(set) var fetchAvailabilityCallCount = 0
    public var fetchAvailabilityHandler: (() throws -> (CloudKitAvailability))?
    public func fetchAvailability() throws -> CloudKitAvailability {
        fetchAvailabilityCallCount += 1
        if let fetchAvailabilityHandler = fetchAvailabilityHandler {
            return try fetchAvailabilityHandler()
        }
        fatalError("fetchAvailabilityHandler returns can't have a default value thus its handler must be set")
    }
}
