///
/// @Generated by Mockolo
///

import CompositeKit

class TagListStoreBuildableMock: TagListStoreBuildable {
    init() { }

    private(set) var buildTagListStoreCallCount = 0
    var buildTagListStoreHandler: (() -> (ViewStore<TagListState, TagListAction, TagListDependency>))?
    func buildTagListStore() -> ViewStore<TagListState, TagListAction, TagListDependency> {
        buildTagListStoreCallCount += 1
        if let buildTagListStoreHandler = buildTagListStoreHandler {
            return buildTagListStoreHandler()
        }
        fatalError("buildTagListStoreHandler returns can't have a default value thus its handler must be set")
    }
}

class TsundocListStoreBuildableMock: TsundocListStoreBuildable {
    init() { }

    private(set) var buildTsundocListStoreCallCount = 0
    var buildTsundocListStoreHandler: ((TsundocListState.Query) -> (ViewStore<TsundocListState, TsundocListAction, TsundocListDependency>))?
    func buildTsundocListStore(query: TsundocListState.Query) -> ViewStore<TsundocListState, TsundocListAction, TsundocListDependency> {
        buildTsundocListStoreCallCount += 1
        if let buildTsundocListStoreHandler = buildTsundocListStoreHandler {
            return buildTsundocListStoreHandler(query)
        }
        fatalError("buildTsundocListStoreHandler returns can't have a default value thus its handler must be set")
    }
}
