fastlane_require "dotenv"

Dotenv.load(".env.secret")

default_platform(:ios)

platform :ios do
  lane :take_snapshots do
    snapshot

    sh("cp '/System/Library/Fonts/SFNSRounded.ttf' ./screenshots/fonts/English.ttf")
    sh("cp '/System/Library/Fonts/ヒラギノ丸ゴ ProN W4.ttc' ./screenshots/fonts/Japanese.ttc")

    frame_screenshots(
      path: "./fastlane/screenshots",
      force_orientation_block: proc do |filename|
        if filename.include? "iPad"
          :landscape_right
        else
          :portrait
        end
      end
    )
  end

  lane :update_development_pp do
    match
  end

  lane :update_appstore_pp do
    match
  end

  lane :release do
    app_store_connect_api_key
    deliver
  end

  lane :release_build_only do
    app_store_connect_api_key
    match
    gym(scheme: "TsunDocs (iOS)", sdk: "iphoneos")
    pilot
    clean_build_artifacts
  end
end

platform :mac do
  lane :update_development_pp do
    match
  end

  lane :update_appstore_pp do
    match
  end
end
