default_platform(:ios)

platform :ios do
  lane :take_snapshots do
    snapshot
  end

  lane :update_development_pp do
    match
  end

  lane :update_appstore_pp do
    match
  end

  lane :release do
    app_store_connect_api_key
    match
    gym
    github_release
    deliver
    clean_build_artifacts
  end

  lane :release_build_only do
    app_store_connect_api_key
    match
    gym
    pilot
    clean_build_artifacts
  end

  private_lane :github_release do
    get_version_number
    changelog_from_git_commits
    set_github_release(
      name: "#{lane_context[SharedValues::VERSION_NUMBER]}",
      tag_name: "v#{lane_context[SharedValues::VERSION_NUMBER]}",
      description: lane_context[SharedValues::FL_CHANGELOG],
      upload_assets: [
        lane_context[SharedValues::IPA_OUTPUT_PATH],
        lane_context[SharedValues::DSYM_OUTPUT_PATH],
      ]
    )
  end
end

platform :mac do
  lane :update_development_pp do
    match
  end

  lane :update_appstore_pp do
    match
  end
end
